### ISSUE TITLE
Ensure Thanos data stays with subsequent Pelorus deployments.

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#139]

**Comment by etsauer** [comment]
https://www.scaleway.com/en/docs/how-to-migrate-object-storage-buckets-with-minio/

**Comment by weshayutin** [comment]
@KevinMGranger please speak to @etsauer regarding this issue to get more details

**Comment by mpryc** [comment]
@weshayutin one of those two is valid until we test, but not both. I think this have better description so will close #477.

**Comment by weshayutin** [comment]
We can test this as we setup for https://github.com/konveyor/pelorus/pull/471

**Comment by mpryc** [comment]
This issue should be closed. We do have PVC for prometheus data with s3 backup possibility. Also an CI job uses persistent s3 to ensure data stays between deployments.

**Comment by mpryc** [comment]
Closing as fixed. Currently data is preserved and documentation updated with the:
https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ProductionBestPractice/
