### ISSUE TITLE
Change the prefix for the failure metrics to `sdp`

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#140]
For consistency's sake, I would like to see all metrics under the `software delivery performance` group be prefixed by `sdp:`. Right now the three failure rules are prefixed with `fr`, I assume for `failure rate`, which doesn't really apply to all three.

The SDP dashboard queries will need to be updated as well as part of this change.

**Comment by KevinMGranger** [comment]
This is currently fixed in the code, but the documentation is out of date.
