### ISSUE TITLE
Jira Failure Exporter does not work with custom cert

### ISSUE THREAD

**Issue by themoosman** [konveyor/pelorus#193]
The Jira failure exporter does not work against a Jira server with a cert signed by an unknown CA.

**Comment by etsauer** [comment]
@themoosman @malacourse do we have a way to spin up a containerized jira server?

**Comment by themoosman** [comment]
@etsauer Would this work?  https://hub.docker.com/r/atlassian/jira-software

**Comment by KevinMGranger** [comment]
Related to #463

**Comment by KevinMGranger** [comment]
This would in fact be fixed by #463, so we'll close this in favor of that issue.
