### ISSUE TITLE
Add backing volumes to prometheus instances

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#205]
This will be an update to our helm charts. Need to configure prometheus to use a pv. There should be a config flag to turn this on and off.

**Comment by mpryc** [comment]
Implemented and documented. Closing:

https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/PelorusCore/#prometheus-persistent-volume

and

https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ProductionBestPractice/
