### ISSUE TITLE
How might we label apps to match with a JIRA issue?

### ISSUE THREAD

**Issue by mvmaestri** [konveyor/pelorus#221]
I see in my failure exporter pod logs with an app=unknown

10-13-2020 13:34:44 INFO     Collected failure_creation_timestamp{ app=unknown, issue_number=MDT-7 } 1600719815.0
10-13-2020 13:34:44 INFO     Collected failure_creation_timestamp{ app=unknown, issue_number=MDT-6 } 1597170899.0
10-13-2020 13:34:44 INFO     Collected failure_resolution_timestamp{ app=unknown, issue_number=MDT-6 } 1597175474.0
10-13-2020 13:34:44 INFO     Collected failure_creation_timestamp{ app=unknown, issue_number=MDT-5 } 1597170854.0

How can I match an app with a JIRA issue? Maybe some label specifications on the docs?

**Comment by etsauer** [comment]
Yes,this is a docs issue.

**Comment by etsauer** [comment]
@mvmaestri if your Jira metrics contain `app=unknown`, that means a card was discovered in Jira that was not labelled according to the configuration on the failure exporter's `APP_LABEL` value which defaults to `app.kubernetes.io/app`. We need to get the docs updated to reflect this.
