### ISSUE TITLE
Integration with Tekton

### ISSUE THREAD

**Issue by mvmaestri** [konveyor/pelorus#224]
To collect commit metrics

**Comment by KevinMGranger** [comment]
There's some sample code related to how this could be achieved in #327.

**Comment by weshayutin** [comment]
This may be booted out of the MVR based on https://github.com/konveyor/pelorus/issues/478

**Comment by weshayutin** [comment]
IMHO the current Tekton demo w/ https://github.com/konveyor/pelorus/pull/587 takes care of this issue

**Comment by weshayutin** [comment]
Documentation is and will continue to filled out here https://github.com/konveyor/pelorus/blob/master/demo/README.md
