### ISSUE TITLE
Upgrade Grafana Operator to most recent version (3.6.0)

### ISSUE THREAD

**Issue by themoosman** [konveyor/pelorus#235]
When installing the Grafana operator on OCP 4.6, it notifies that Grafana has an available update.

**Comment by themoosman** [comment]
![Selection_359](https://user-images.githubusercontent.com/532487/98829002-55052d00-23fe-11eb-842d-6072df0f8495.png)

**Comment by themoosman** [comment]
A potential issue with #210

**Comment by KevinMGranger** [comment]
Operator version lag is related to the root cause of #321.

**Comment by mpryc** [comment]
With the PR #389 we updated Graphana to 4.2.0
