### ISSUE TITLE
GitLabCommitCollector needs performance improvement

### ISSUE THREAD

**Issue by willowmck** [konveyor/pelorus#244]
Due to the nature of GitLab project searching, finding the correct project id to gather commit metrics is extremely time consuming and has the potential to make the prometheus scraper timeout (default scraper timeout value is 10 seconds).

**Comment by themoosman** [comment]
When I originally wrote the collect it had a map to cache project ids.  I'm not sure why I removed it but I did.  The would help as you'd only have to do the search 1x.

**Comment by willowmck** [comment]
@themoosman I seem to remember that being in the code as well.  Okay, I will work on adding it back in.

**Comment by mpryc** [comment]
Testing made easy:

1. In the pelorus dir create app.py
```
cat <<EOF > app.py
#!/usr/bin/env python3
print("Hello World")
EOF

chmod +x app.py
```

2. Create namespace for build and run the build, annotate with existing gitlab url and hash
```
export NS=buildtest
export BUILD_NAME=gitlab-binary-build

oc create namespace "${NS}"
oc config set-context --current --namespace "${NS}"

oc new-build python --name="${BUILD_NAME}" --binary=true
oc label bc "${BUILD_NAME}" app.kubernetes.io/name="${BUILD_NAME}"

oc start-build bc/"${BUILD_NAME}" --from-file=./app.py --follow

oc annotate build "${BUILD_NAME}"-1 --overwrite \
io.openshift.build.commit.id=b807fd8e1b2bd1755eca14960e5352fe89ff466e \
io.openshift.build.source-location=https://gitlab.com/mpryc/pelorus-gitlab
```

3. Run the gitlab collector with the given build/namespace
```
export GIT_PROVIDER=gitlab
export NAMESPACES="${NS}"
python exporters/committime/app.py
```

4. Confirm the timestamp was correctly "collected"

```
07-21-2022 13:19:56 INFO     Collected commit_timestamp{ namespace=buildtest, app=gitlab-binary-build, commit=b807fd8e1b2bd1755eca14960e5352fe89ff466e, image_sha=sha256:cc4e6a5c159edb6477d7b07f8a82a1708201a4a218151fd1f1616d7a2daeafaa } 1658312875.0
```
