### ISSUE TITLE
Jenkins on OpenShift and mult-branch

### ISSUE THREAD

**Issue by tdbeattie** [konveyor/pelorus#246]
Pelorus depends on jenkinsPipelineStrategy and is designed to work with Jenkins builds in OpenShift. We have some engagements that use Jenkins on top of OpenShift and uses multi branch strategy. 

This issue is to discuss and align on a solution that will enable Pelorus to work with Jenkins using multi branch.

**Comment by mpryc** [comment]
As noted in the https://bugzilla.redhat.com/show_bug.cgi?id=1785291 the JenkinsPipelineStrategy is deprecated from OpenShift version 4.3.z.

With that I am closing this issue. Note that we currently have a way of configuring Pelorus with images using image exporter documented at:
https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterCommittime/#using-commit-time-with-images
