### ISSUE TITLE
Proposal: split code and config into separate repos

### ISSUE THREAD

**Issue by shaheinm** [konveyor/pelorus#255]
Particularly if a user chooses to deploy/use Pelorus in a GitOps environment (i.e. using a tool like ArgoCD watching a specific repository), helm charts should be in a separate repository as Argo would run syncs on every code commit when the charts did not change.

This would also enable a user to pull only the charts repo and edit the values file to deploy (in an ideal world, I'm also imagining Pelorus images available to pull and run from Quay, DockerHub, etc).

**Comment by mpryc** [comment]
We have changed the installation method to be based off OpenShift Pelorus Operator. Closing this as it's not relevant anymore. Please follow the installation documentation:
https://pelorus.readthedocs.io/en/latest/GettingStarted/Installation/
