### ISSUE TITLE
Change Failure Rate metric not showing

### ISSUE THREAD

**Issue by varodrig** [konveyor/pelorus#272]
Preconditions:

- I have Pelorus operators and stack installed
- I have the demo application running:
sed -i '/source_code_url:/c\source_code_url: https://github.com/varodrig/container-pipelines.git' .applier/group_vars/seed-hosts.yml
sed -i '/skip_manual_promotion:/c\skip_manual_promotion: true' .applier/group_vars/seed-hosts.yml
ansible-playbook -i ./.applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml

- I have setup and configured the Failure Time Exporter.
- I have already setup a Jira account and created at least 2 tickets. 

For more detail steps and information:

Labs

https://github.com/redhat-gpe/ocp4_pelorus/blob/pelorus-lab/modules

This issue appears on the Failure section. 

Steps to reproduce:

- Go to Grafana Dashboard - > Software Delivery Performance - By App 
- Select the application basic-nginx

It seems it's associated to the Mean Time to Restore metric, it's not showing the metric unless the issues are being closed.  the pod logs is showing collecting metrics however, Grafana is not showing the metric until I closed a ticket.

**Comment by varodrig** [comment]
to verify this when QA the lab. it seems it's working fine.

**Comment by weshayutin** [comment]
@varodrig this should be working for you now.  Lots of updates, fixes, and doc updates. Please open a new issue if you have the problem again.  Thank you
