### ISSUE TITLE
Change since last interval not showing

### ISSUE THREAD

**Issue by varodrig** [konveyor/pelorus#273]
Preconditions:

- I have Pelorus operators and stack installed
- I have the demo application running:
sed -i '/source_code_url:/c\source_code_url: https://github.com/varodrig/container-pipelines.git' .applier/group_vars/seed-hosts.yml
sed -i '/skip_manual_promotion:/c\skip_manual_promotion: true' .applier/group_vars/seed-hosts.yml
ansible-playbook -i ./.applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml

- I have setup and configured the Failure Time Exporter.
- I have already setup a Jira account and created at least 2 tickets. 

For more detail steps and information:

Labs

https://github.com/redhat-gpe/ocp4_pelorus/blob/pelorus-lab/modules

This issue appears on the Failure section. 

Steps to reproduce:

- Go to Grafana Dashboard - > Software Delivery Performance - By App 
- Select the application basic-nginx

Change since last interval is not showing for a while. After several minutes it's showing 0%. 
![Screenshot 2021-04-12 at 11 29 29 PM](https://user-images.githubusercontent.com/64439402/114599740-827e2d00-9c61-11eb-9989-fe2b63997ea7.png)

**Comment by varodrig** [comment]
workaround use 5 mins by default.

**Comment by varodrig** [comment]
when exporters didn't exist is showing N/A.

**Comment by varodrig** [comment]
I'm good with the workarounds. I'll be updating the lab.

**Comment by mpryc** [comment]
I am closing this issue. 

We have new documentation for the demo, where there is a note https://pelorus.readthedocs.io/en/latest/GettingStarted/QuickstartTutorial/#view-the-pelorus-measurements :

"
Note: If the time elapsed from your mongo-persistent deployment is higher then 5 minutes, you may want to adjust different relative time range ⓵ e.g. Last 3 hours.
"


Also we have another issue around documenting or changing the default time  interval: https://github.com/konveyor/pelorus/issues/499
