### ISSUE TITLE
No data in MTTR and change to failure graphic

### ISSUE THREAD

**Issue by varodrig** [konveyor/pelorus#274]
Preconditions:

- I have Pelorus operators and stack installed
- I have the demo application running:
sed -i '/source_code_url:/c\source_code_url: https://github.com/varodrig/container-pipelines.git' .applier/group_vars/seed-hosts.yml
sed -i '/skip_manual_promotion:/c\skip_manual_promotion: true' .applier/group_vars/seed-hosts.yml
ansible-playbook -i ./.applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml

- I have setup and configured the Failure Time Exporter.
- I have already setup a Jira account and created at least 2 tickets. 

For more detail steps and information:

Labs

https://github.com/redhat-gpe/ocp4_pelorus/blob/pelorus-lab/modules

This issue appears on the Failure section. 

Steps to reproduce:

- Go to Grafana Dashboard - > Software Delivery Performance - By App 
- Select the application basic-nginx

![image](https://user-images.githubusercontent.com/64439402/114601843-f7eafd00-9c63-11eb-9bee-5bd09dae0a59.png)

**Comment by varodrig** [comment]
relates with issue 273.

**Comment by varodrig** [comment]
![image](https://user-images.githubusercontent.com/64439402/117198658-48fb9600-adb7-11eb-8fe5-6fe25aba6882.png)
it's still happening.

**Comment by etsauer** [comment]
The App dashboard needs updated to use the proper queries here.
