### ISSUE TITLE
Pin to versions in the requirements file

### ISSUE THREAD

**Issue by springdo** [konveyor/pelorus#276]
currently the exporters pull latest for most of the dependencies. This means the OpenShift module is pulling v12 or greater which is using the Kubernetes v12 module too. These versions should be fixed to guarantee the correct module is pulled for the exporters

**Comment by themoosman** [comment]
Related to #262

**Comment by mpryc** [comment]
With the merge of #406 I consider this issue as resolved. We do have clear documentation on which required PyPI package is used by which exporter. On top of that we did pin the dependencies that had to be used at minimal version:

```
openshift == 0.13.1    # module openshift
python-gitlab >= 2.4.0 # module gitlab
```

Pinning other modules is not really desired as we would not use bug fixes and security fixes from those modules, so we should use latest released versions of those.

We also switched to use pre-built quay images as main method of deployment, meaning packages are exactly the ones we used when building podman images.
