### ISSUE TITLE
PR checks should make sure docs build and be previewable

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#299]
This could be done using `mkdocs` in a workflow, or via readthedocs' "Build pull requests for this project " feature, which we're looking into now.

**Comment by KevinMGranger** [comment]
It looks like RTD needs more permissions on the organization itself for this to work. Eric is going to look into that.

**Comment by etsauer** [comment]
@KevinMGranger now that we've got RTD permissions updated, we can see it adding a check to our PRs (see #296 ). Should we close based on that?

**Comment by KevinMGranger** [comment]
@etsauer I'm wondering what the optimal workflow is for this. Perhaps a workflow / action that checks for modifications to `docs`, and if there are any, posts a comment with the link to the RTD stuff?

**Comment by KevinMGranger** [comment]
Oh, I hadn't seen what it looks like in the workflow run. That fits the bill!
