### ISSUE TITLE
Replace images that require entitlements with the upstream versions

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#311]
In order to support installs on k8s, we need to make sure we are only using images that are publicly accessible.

Doing a quick search finds several images pulling from registry.redhat.io:

https://github.com/konveyor/pelorus/search?q=registry.redhat.io

This will result in non-OpenShift Container Platform clusters throwing this error:

```
 Warning  Failed          39s (x4 over 2m10s)  kubelet            Failed to pull image "registry.redhat.io/openshift4/ose-cli:v4.4": rpc error: code = Unknown desc = Error response from daemon: Head https://registry.redhat.io/v2/openshift4/ose-cli/manifests/v4.4: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
```

We need to find the upstream versions of these images so that community members can use Pelorus.

**Comment by etsauer** [comment]
There are the images we need to find replacements for:

- registry.redhat.io/openshift4/ose-cli:v4.4
- registry.redhat.io/openshift4/ose-oauth-proxy:v4.5
- registry.redhat.io/web-terminal-tech-preview/web-terminal-tooling-rhel8:1.0.1

**Comment by fmenesesg** [comment]
This should be the replacement:

registry.redhat.io/openshift4/ose-cli:v4.4 --> docker pull quay.io/openshift/origin-cli:4.4
registry.redhat.io/openshift4/ose-oauth-proxy:v4.5 --> docker pull quay.io/openshift/origin-oauth-proxy:4.5
registry.redhat.io/web-terminal-tech-preview/web-terminal-tooling-rhel8:1.0.1 --> docker pull quay.io/wto/web-terminal-tooling:1.0

There are updated images on all the repositories maybe we can try them, or maybe use the same openshift version images.

**Comment by etsauer** [comment]
@fmenesesg by "updated images" you mean newer tags? If so, then yes I think we should try to update them while we are making this change.

**Comment by fmenesesg** [comment]
@etsauer , yes I mean newer tags :)
