### ISSUE TITLE
Correct steps in installation instructions https://pelorus.readthedocs.io/en/latest/Install/

### ISSUE THREAD

**Issue by rdy-rh** [konveyor/pelorus#313]
https://pelorus.readthedocs.io/en/latest/Install/
These steps worked in OCP4.8.2 baremachine:

    # clone the repo (you can use a different release or clone from master if you wish)
    git clone https://github.com/konveyor/pelorus
    cd pelorus
    # make sure you are in master branch : git checkout master
    oc create namespace pelorus
    helm install operators charts/operators --namespace pelorus
    # Verify the operators are completely installed before installing the pelorus helm chart
    helm install pelorus charts/pelorus --namespace pelorus

**Comment by KevinMGranger** [comment]
Based on our discussion [in this `build failing` issue](https://github.com/konveyor/pelorus/issues/303#issuecomment-881511138), we want to create a `stable` branch and push people towards that.

This is yet another instance of the same issue, where the default installation points towards master for the exporter even though it might be 1.3.0 for the helm charts.

**Comment by weshayutin** [comment]
I think 1.3.0 also pointed at an old python3.8 container and the python deps failed.

**Comment by KevinMGranger** [comment]
We have identified the issue and mostly solved it. It should be included in the 1.4 release. More details can be found in #329, but for now I'll close this as a duplicate.
