### ISSUE TITLE
Deploy pelorus to another cloud provider (AKS/GKE/EKS)

### ISSUE THREAD

**Issue by nhat-tong** [konveyor/pelorus#319]
Hello,

Thanks for your work on this open source project. These metrics sounds really interesting!

I don't have an OpenShift cluster. At his place, could we deploy this solution to AKS/GKE/EKS ?

Thanks in advance,

**Comment by KevinMGranger** [comment]
[Kubernetes support](#328) is planned! Once it is supported, you should be able to deploy to AKS/GKE/EKS.

If you urgently want to use Pelorus and you're already targeting AWS, you could look into [ROSA](https://aws.amazon.com/rosa/) as an alternative to EKS.
