### ISSUE TITLE
Unable to install pelorus on openshift version 4.9.9

### ISSUE THREAD

**Issue by metaversed** [konveyor/pelorus#321]
Steps followed

    git clone --depth 1 --branch v1.3.0 https://github.com/konveyor/pelorus
    cd pelorus
    oc create namespace pelorus
    helm install operators charts/operators --namespace pelorus

After above step is performed , received below error on terminal
```
elorus git:(cfff5f2) helm install operators charts/operators/ --namespace pelorus --debug                                     
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /Users/raghurambanda/repos/pelorus/charts/operators

client.go:128: [debug] creating 6 resource(s)
wait.go:48: [debug] beginning wait for 6 resources with timeout of 5m0s
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job installplan-approver with timeout of 5m0s
client.go:556: [debug] Add/Modify event for installplan-approver: ADDED
client.go:595: [debug] installplan-approver: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for installplan-approver: MODIFIED
client.go:595: [debug] installplan-approver: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:88: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
```

    # Verify the operators are completely installed before installing the pelorus helm chart
`    helm install pelorus charts/pelorus --namespace pelorus`

```
➜  pelorus git:(cfff5f2) oc get sub -n pelorus
NAME               PACKAGE            SOURCE 
               CHANNEL
grafana-operator   grafana-operator   community-operators   alpha
prometheus         prometheus         community-operators   beta
```

![Screenshot 2021-12-10 at 13 39 30](https://user-images.githubusercontent.com/49312566/145583016-ba7747ff-112e-40ed-9f69-93ae274ebb83.png)

![Screenshot 2021-12-10 at 13 42 31](https://user-images.githubusercontent.com/49312566/145583193-9b368ef9-3988-465c-974d-452f716d8312.png)

![Screenshot 2021-12-10 at 13 43 24](https://user-images.githubusercontent.com/49312566/145583302-b6c1ae31-f4ca-44f6-b06a-69cb7819829f.png)

**Comment by KevinMGranger** [comment]
I don't have a 4.9 cluster handy to test this. The operators are working just fine on 4.7.9. Can you try the following:

In `charts/operators/templates/prometheus-subscription.yaml`, change

      startingCSV: prometheusoperator.0.37.0

to

      startingCSV: prometheusoperator.0.47.0

?

**Comment by metaversed** [comment]
@KevinMGranger  Tried this but no luck. Its still the same error as before

**Comment by kpiwko** [comment]
Hello @metaversed @KevinMGranger , I was able to install operators on 4.9.8 with following changes:

https://github.com/kpiwko/pelorus/commit/7268231f1022edb29cfce60b9ee17f14c1aa3b0e

However, I'm stuck in installing Pelorus itself afterwards:

```
➜  pelorus git:(7268231) helm install pelorus charts/pelorus --namespace pelorus --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/kpiwko/devel/pelorus/pelorus/charts/pelorus

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec
helm.go:81: [debug] error validating "": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec
helm.sh/helm/v3/pkg/kube.scrubValidationError
	/builddir/build/BUILD/src/helm.sh/helm/pkg/kube/client.go:596
helm.sh/helm/v3/pkg/kube.(*Client).Build
	/builddir/build/BUILD/src/helm.sh/helm/pkg/kube/client.go:189
helm.sh/helm/v3/pkg/action.(*Install).Run
	/builddir/build/BUILD/src/helm.sh/helm/pkg/action/install.go:263
main.runInstall
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:960
github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:897
main.main
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/lib/golang/src/runtime/proc.go:204
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1374
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/builddir/build/BUILD/src/helm.sh/helm/pkg/action/install.go:265
main.runInstall
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:960
github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:897
main.main
	/builddir/build/BUILD/src/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/lib/golang/src/runtime/proc.go:204
runtime.goexit
	/usr/lib/golang/src/runtime/asm_amd64.s:1374
```

Any suggestions? I'm also happy to debug further / provide access to that cluster @KevinMGranger

**Comment by pmacik** [comment]
FYI: 4.9+ openshift clusters do not provide `CustomResourceDefinition` API version `v1beta1` - only `v1` and since for instance `grafna-operator.v3.5.0` uses `v1beta1` CRD API - it would not work with openshift 4.9+

The change @kpiwko has made (changing grafana-operator version from `3.5.0` to `4.0.1` fixes that problem because starting with `v3.10.4` that operator uses `v1` CRD API.

@kpiwko I guess that the error `Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec` is caused by the helm chart assuming/depending on `v3.5.0` of `GrafanaDashboard` but with `v4.0.1` that API has changed.

**Comment by KevinMGranger** [comment]
Thank you all for the thorough investigation!

We'll have to see if the newer operator versions support the earlier versions of OpenShift we want to support. If so, modernizing them should be fine.

If they don't, then we'll have to just do heavier templating for some of our charts.

**Comment by weshayutin** [comment]
This should be working on 4.9 from pelorus master now.  Please confirm @metaversed
