### ISSUE TITLE
Refactor JIRA based Failure Exporter

### ISSUE THREAD

**Issue by kpiwko** [konveyor/pelorus#336]
An umbrella task to refactor JIRA based Failure Exporter to address multiple [issues reported](https://github.com/konveyor/pelorus/labels/jira)

* #193 Custom Certificate for JIRA
* #304 Limited results of exporter to 50 results
* #118 Service Account authentication
* #221 App Labes matching
* #278 Failures with missing scrum template

There are additional _hard-coded_ values in the exporter what would yield to issues in gathering the data (issue type that might not exist and leads to #278 and priority that might be different in the schema).
There is also a request to be able to fetch only recently updated issues in the [source](https://github.com/konveyor/pelorus/blob/8b50c0c0178b2be6625bca77e4dbb32fef958297/exporters/failure/collector_jira.py#L24).
Another open question is related to handling already closed issues (would it make any sense to fetch them)

Suggestion how to enhance the exporter:

1. Provide updates to query function to handle pagination
2. Provide more flexibility to JIRA client creation (to enable certs, service account)
3. Provide more flexible way how to define Jira Schema(s) to be queried. This to me means exposing JQL and providing some nice abstractions that users could configure only a part of it as reasonable default.

Thinking alongside [these lines](https://github.com/kpiwko/jira-miner/blob/main/src/jira/JiraSchema.ts#L1-L14https://github.com/kpiwko/jira-miner/blob/main/src/jira/JiraSchema.ts#L1-L14), what I would suggest wrt 3.:

* JIRA_JQL query to give users ability to provide full query.
* More complex JQL template: `project in ($PROJECTS) and type in ($TYPES) and priority in ($PRIORITIES) and updated >= $AGE` would improve flexibility however is not bullet-proof. There might be no `priority` field (although it looks like JIRA client already abstracts that) and some complex queries might require different mapping of type/priority per project. I wonder, in such case, what would happen if we configure two instances of JIRA Failure Exporter? Would that work, do you happen to know?

Result would be new variables / config:
* JQL
* PROJECTS
* TYPES
* PRIORITIES
* AGE

And some reasonable default and logic that contracts the JQL based on what is provided.

I'm confident to implement 1. and 3. quickly. 2. would require more effort, especially to validate. What do you think folks?

**Comment by mpryc** [comment]
I am closing this umbrella issue as all of the sub-issues were resolved. Please do create new issues if additional work is needed for the JIRA exporter.

Thanks again for the work !
