### ISSUE TITLE
Openshift support matrix / testing strategy / support policy

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#345]
- We need to document what versions of openshift are explicitly supported.
- We need a strategy to automate testing on each of those versions.
- We need to document what our support policy is (e.g. how old / new of an openshift release do we support?)

[There's an outstanding issue for installing on 4.9](https://github.com/konveyor/pelorus/issues/321). As part of our testing strategy, we should look at prerelease versions.

[The installation prerequisites](https://pelorus.readthedocs.io/en/latest/Install/#prerequisites) say you can use a cluster on 3.11 or higher, but has 3.11 been tested recently?

WDH - We will suport 4.9, 4.10, and soon 4.11

**Comment by weshayutin** [comment]
@weshayutin  will close this.. we're good here
