### ISSUE TITLE
Docs reference old, missing runhelm.sh script

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#347]
https://pelorus.readthedocs.io/en/latest/MinIO/#update-pelorus-configuration

**Comment by RishiKumarRay** [comment]
can you elaborate this?

**Comment by KevinMGranger** [comment]
> can you elaborate this?

Sure thing! The last section, "Update Pelorus Configuration", says to use the `./runhelm.sh` script. But it looks like that was deleted a while ago-- we have to figure out what that script did and put its equivalent in the documentation.

**Comment by mpryc** [comment]
Fixed as part of the PR #558
