### ISSUE TITLE
Invalid tag 1.4.1

### ISSUE THREAD

**Issue by rafamqrs** [konveyor/pelorus#349]
Hi all, 

I've tried to deploy the pelorus, but I got an error message: 
"Cloning "https://github.com/redhat-cop/pelorus.git" ...
error: fatal: couldn't find remote ref 1.4.1"

**Comment by KevinMGranger** [comment]
It looks like I made a typo in the configuration.

In your exporter configuration, if you set `source_ref: v1.4.1`, that will fix it.

**Comment by rafamqrs** [comment]
Sure @KevinMGranger, I did it! But there is a default value with the wrong value. 

I'm not sure if it is the best way, but I've created a pull request with the fix to this issue.
