### ISSUE TITLE
Create image per pelorus exporter

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#358]
Currently pelorus exporter images are the same.

The path_context is exactly the same for 3 different exporters resulting in the images being exactly the same.

[https://github.com/konveyor/pelorus/blob/master/.github/workflows/build-pelorus.yaml#L32](https://github.com/konveyor/pelorus/blob/master/.github/workflows/build-pelorus.yaml#L32
)

There should be separation on how exporters are being built/tested/provided and not being all in one.

Currently the exporters are available at:
[https://quay.io/repository/pelorus/failure-exporter](https://quay.io/repository/pelorus/failure-exporter
)
[https://quay.io/repository/pelorus/committime-exporter](https://quay.io/repository/pelorus/committime-exporter
)
[https://quay.io/repository/pelorus/deploytime-exporter](https://quay.io/repository/pelorus/deploytime-exporter)

If we inspect each of the container it's exactly the same, e.g.

```
# podman run -ti --name  deploytime-exporter --hostname deploytime --network host d9509bae4bc7 /bin/bash
(app-root) ls
committime  deploytime	failure  pelorus  README.md  requirements-dev.txt  requirements.txt  setup.py  tests
(app-root) pwd
/opt/app-root/src

```

**Comment by KevinMGranger** [comment]
Related: #276

**Comment by mpryc** [comment]
This is closed, however comment is desired.

We do create quay.io images and tag them correctly during release process.

This is done via github actions:

Build action which builds and tags the image with it's sha and "latest" tag on every PR merged:
    https://github.com/konveyor/pelorus/blob/master/.github/workflows/build-pelorus.yaml

Release action to tag the images with "stable" tag on release event, from the latest image sha:
    https://github.com/konveyor/pelorus/blob/master/.github/workflows/release.yaml

Pre-release action which tags the images on release and pre-release with it's version from the latest image sha:
    https://github.com/konveyor/pelorus/blob/master/.github/workflows/pre-release.yaml

The resulting images:
    https://quay.io/repository/pelorus/committime-exporter?tab=tags
    https://quay.io/repository/pelorus/failure-exporter?tab=tags
    https://quay.io/repository/pelorus/deploytime-exporter?tab=tags


There is still room for improvement as s2i have same code stored in each image, the difference is app.py being invoked, so we could get rid of the code from other exporters then the one for which image is built.
