### ISSUE TITLE
Document and cleanup python requirements*

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#359]
As a result of conversation from: #https://github.com/konveyor/pelorus/pull/353

From @KevinMGranger:

We should document:

all of our dependencies
rationale behind using them
if they're pinned to a version, why that's the case

Currently they are in the:
[pelorus/exporters/requirements.txt](https://github.com/konveyor/pelorus/blob/master/exporters/requirements.txt)
[pelorus/exporters/requirements-dev.txt](https://github.com/konveyor/pelorus/blob/master/exporters/requirements-dev.txt)

**Comment by KevinMGranger** [comment]
Related: #276
