### ISSUE TITLE
Automate validation of Pelorus deployment

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#36]

**Comment by etsauer** [comment]
What we need:

- Shell script to run for install
- Shell script for running validation tests
- How to handle logging into Prometheus, Grafana, etc.

**Comment by ramius345** [comment]
Things I check:

routes should 200:
$ oc get routes
NAME                 HOST/PORT                                               PATH   SERVICES             PORT      TERMINATION          WILDCARD
grafana-proxy        grafana-proxy-pelorus.apps.ci-1.cop.rht-labs.com               grafana-proxy        web       reencrypt/Redirect   None
prometheus-pelorus   prometheus-pelorus-pelorus.apps.ci-1.cop.rht-labs.com          prometheus-pelorus   web-tls   reencrypt/Redirect   None
[ramius@greengrape noobaa-operator] (master=)


on the grafana one, go to the metrics dashboard:
https://grafana-proxy-pelorus.apps.ci-1.cop.rht-labs.com/d/bOroJ8-Wk/devops-software-delivery-metrics?orgId=1

Then check average lead time and change failure rate are reporting values

![image](https://user-images.githubusercontent.com/1661189/70471390-ac827680-1a92-11ea-89cb-1509b54834df.png)


![image](https://user-images.githubusercontent.com/1661189/70471411-b73d0b80-1a92-11ea-8f0d-fe328b533e60.png)

Then check connections in prometheus under targets:
https://prometheus-pelorus-pelorus.apps.ci-1.cop.rht-labs.com/targets

Make sure they are all in an up state.

**Comment by sbailleu** [comment]
@kkoller Please look into this issue to split it into smaller pieces of work

**Comment by sbailleu** [comment]
- Automate validation of Pelorus deployment
> Verifying that all components come up successfully (health check)
- Code quality
> Python code quality scanner (figure out what to use, no external hosted service)

(ideas: https://github.com/features/actions; pylama)

**Comment by sbailleu** [comment]
Update card names and creating a second one as per the comment above

**Comment by jtudelag** [comment]
@etsauer would it be ok to just use selenium or similar (cypress maybe?) to check that we can log in into Grafana/OCP and that all targets are "Up" in Prometheus?

I mean, that way we cover the E2E, and we don't need a script to check Pods running, etc.

**Comment by jtudelag** [comment]
@etsauer would it be ok to just use selenium or similar (cypress maybe?) to check that we can log in into Grafana/OCP and that all targets are "Up" in Prometheus?

I mean, that way we cover the E2E, and we don't need a script to check Pods running, etc.

**Comment by weshayutin** [comment]
This is now done in prow ci
