### ISSUE TITLE
Should pelorus cut out the Prometheus/Grafana operators?

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#369]
To this point, Pelorus has relied on two community operators to get its datasource (prometheus) and its front-end dashboarding tool (grafana) up and running. However, this dependency on Operators that we don't control, and the Operator Lifecycle Manager process has created quite a few problems that we don't have enough control/influence to resolve quickly.

I'm opening this issue to officially start a conversation about whether the convenience of the operators are worth the trouble. I'm also going to link a few of our open issues to this to show things that we currently can't fix.

**Comment by etsauer** [comment]
One downside to this approach that I just thought of today is that moving away from the operators would make things like our Thanos setup REALLY cumbersome to re-engineer.

**Comment by mpryc** [comment]
I am closing this issue. Currently Helm Chart was moved into Pelorus Operator based on the helm charts.

The split of deployment/observability is tracked under discussion: https://github.com/konveyor/pelorus/discussions/809

Will reference this issue in the discussion.
