### ISSUE TITLE
At least one reviewer should happen before push btn is enabled

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#409]
With introduction of OpenShift CI robot there is no longer requirement of one person to review the code before enabling the Merge btn in the github UI. That should be changed.

**Comment by KevinMGranger** [comment]
@weshayutin any ideas on why this is happening?

**Comment by weshayutin** [comment]
@mpryc @KevinMGranger agreed.. I'll see what I can find out.

**Comment by KevinMGranger** [comment]
Might not be fixed yet, still testing. See comment in #414

**Comment by KevinMGranger** [comment]
Let's test this today @mpryc @mateusoliveira43

**Comment by mateusoliveira43** [comment]
tested here https://github.com/konveyor/pelorus/pull/829

I believe it is safe
![Screenshot from 2023-01-31 16-20-52](https://user-images.githubusercontent.com/66965232/215861450-60985351-be9d-4f24-a7f3-3ea0f6655c01.png)

I can not merge without 1 approve (and I cannot approve myself)
![Screenshot from 2023-01-31 13-55-36](https://user-images.githubusercontent.com/66965232/215861568-af594c7a-0319-494b-946a-7009261b969f.png)
