### ISSUE TITLE
Prometheus via pelorus is not getting data for app commit-time, builds, deploy

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#426]
## Prior to Pelorus install
* mysql-persistent namespace exists 
*  todolist-app builds and triggers builds from commits... ( preexisting pelorus in this case ).  
* /me notes I get the same result when the app is built after deploying pelorus.

## app details
* build-config: https://termbin.com/fjch
* build number 11 yaml: https://termbin.com/1y4f

* install log https://termbin.com/q7po
* Post Setup:
Commit-time exporter: https://termbin.com/fvpt
	Log:  https://termbin.com/f9cz
Deploy-time exporter: https://termbin.com/fa2m

* One can see in the various logs that “namespace=mysql-persistent, app=todolist-mariadb-go” is found by the exporters, but it’s not registered w/ Prometheus and not showing up in grafana.

## Prometheus status after deploy
![gnome-shell-screenshot-cfx3z7](https://user-images.githubusercontent.com/138787/164358533-85c2c73e-8321-4bb7-b401-f119dd8ff002.png)
![gnome-shell-screenshot-cfx3z7](https://user-images.githubusercontent.com/138787/164358729-b1884a87-47e0-4a77-8ceb-d23b8f03b7c2.png)
![gnome-shell-screenshot-gnp6l3](https://user-images.githubusercontent.com/138787/164358965-f3294b51-94a7-4c85-8aa6-53d14a1e68f9.png)

## try a new build
Let’s try a new commit and build w/ todolist-mariadb-go
Here’s where we’re starting…. 

![gnome-shell-screenshot-25xyyj](https://user-images.githubusercontent.com/138787/164359023-2d9f7e12-52b8-4702-a71a-68236d8c83ae.png)

```
commit 2288bdbda4a19047998bfdffbd6b26e8e27c98f3 (HEAD -> main, origin/main, origin/HEAD)
Author: Wesley Hayutin <whayutin@redhat.com>
Date:   Wed Apr 20 12:52:47 2022 -0600

    test5

commit 0a29efca1a102bbfc2fea14e0049d7a8cdb24371
Author: Wesley Hayutin <whayutin@redhat.com>
Date:   Wed Apr 20 12:49:25 2022 -0600

    test4
```
* Push a new commit
````
commit bb48e456571a2262159d31da17eef37dc52261dc (HEAD -> main, origin/main, origin/HEAD)
Author: Wesley Hayutin <whayutin@redhat.com>
Date:   Wed Apr 20 20:03:59 2022 -0600

    test6

commit 2288bdbda4a19047998bfdffbd6b26e8e27c98f3
Author: Wesley Hayutin <whayutin@redhat.com>
Date:   Wed Apr 20 12:52:47 2022 -0600
````
* Build # 11 Completes..
![gnome-shell-screenshot-fyecoz](https://user-images.githubusercontent.com/138787/164359194-d2aed5c6-d748-4a6d-9437-a3051757c566.png)

* Compare local commit to the committime exporter.
```
[whayutin@thinkdoe todolist-mariadb-go]$ git log
commit bb48e456571a2262159d31da17eef37dc52261dc (HEAD -> main, origin/main, origin/HEAD)
Author: Wesley Hayutin <whayutin@redhat.com>
Date:   Wed Apr 20 20:03:59 2022 -0600

# HELP commit_timestamp Commit timestamp
# TYPE commit_timestamp gauge
commit_timestamp{app="todolist-mariadb-go",commit="2288bdbda4a19047998bfdffbd6b26e8e27c98f3",image_sha="sha256:c98bd4c53d92061b51ae9198103d123cb33264d3bca50cf1f16d1bad499ffaec",namespace="mysql-persistent"} 1.650480767e+09
commit_timestamp{app="todolist-mariadb-go",commit="bb48e456571a2262159d31da17eef37dc52261dc",image_sha="sha256:674770c0ca1523200fe750e79aaf01044e1c9dff130420e9e262d1f543c8895e",namespace="mysql-persistent"} 1.650506639e+09
commit_timestamp{app="todolist-mariadb-go",commit="7215e17a1ea96bec76ea5ec46a7bc2328b93e0bb",image_sha="sha256:7dd8b1649d2220661d5144aa40348091f20df302e540b0c5cd8adbcbc63cbdaa",namespace="mysql-persistent"} 1.650479615e+09
commit_timestamp{app="todolist-mariadb-go",commit="8feb2ae431dca6951eb02441da6200c3d5676f21",image_sha="sha256:6aee205c48ffce4cca7e561bcae91c81c183373a06db50d97ce33ebcabcc23ba",namespace="mysql-persistent"} 1.650480055e+09
commit_timestamp{app="todolist-mariadb-go",commit="0a29efca1a102bbfc2fea14e0049d7a8cdb24371",image_sha="sha256:f9e1c2f5d36b3204dc499c11a01c6fb835be19ab5ddbbaf8c2f0524071350840",namespace="mysql-persistent"} 1.650480565e+09
commit_timestamp{app="committime-github",commit="26c59cef28d8e70d50f31bf290f42b5089aa708f",image_sha="sha256:ddef5cb23708997984c99241eed00454b5659aa9e3ed2b36cd4f63edce894d5c",namespace="pelorus"} 1.649754049e+09
commit_timestamp{app="deploytime-exporter",commit="26c59cef28d8e70d50f31bf290f42b5089aa708f",image_sha="sha256:a0b8a6e38b34217002de01f3927abc096e67f968da172e2b7c5443c931d93d4b",namespace="pelorus"} 1.649754049e+09
```

* The commit is found in the commit-time exporter, no errors in the console logs.

## Result
* prometheus still has not registered the application todolist-mariadb
![gnome-shell-screenshot-ay6oee](https://user-images.githubusercontent.com/138787/164360429-88859b7d-d3f4-4717-ae57-772d665b69b8.png)

## Expected Result...
* Pelorus and Prometheus are properly monitoring the commit time, build time, etc..

**Comment by KevinMGranger** [comment]
In a chat with @weshayutin, we determined that since the app was never deployed, there was no data to gather.

We should create a new issue outlining how to clear up this confusion:

- we need a short guide illustrating what resources are necessary for metrics to be gathered (e.g. running pods, jira issues with certain labels, etc.)
- we should have a troubleshooting section in our docs that covers "why can't I see anything?"
We need to make this case more discoverable in grafana:
- have the untracked commits / deployments and unknown issues panels link to the above troubleshooting question
- have some sort of view that makes the uncorrelated raw data easier to see?
  - we'd maybe need some other prometheus rules: right now, filtering per-app is done by _measures_, not metrics. It would have to be by-metric.
  - Maybe this is something that an operator / configuration UI could / should handle.
