### ISSUE TITLE
MinIO documentation is out of date

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#438]
(See also: https://github.com/konveyor/pelorus/issues/347)

In addition to the missing script, the helm chart has been frozen. The new recommended workflow is using the MinIO operator.

- [ ] Adapt the workflow to use the operator - new issue
- [ ] Eventually integrate w/ Pelorus Helm Charts - new issue
- [ ] Update the documentation

**Comment by mpryc** [comment]
I am starting to get convinced that MinIO documentation should be replaced by noobaa as it's easier to setup and run as S3 provider for the project.

**Comment by mpryc** [comment]
This is fixed and in review as part of the https://github.com/konveyor/pelorus/pull/558

We replaced minio recommendations with the noobaa.

**Comment by mpryc** [comment]
Fixed as part of the PR #558. Removed MinIO and replaced by NooBaa
