### ISSUE TITLE
Allow jira exporter to work with different types and priorities

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#439]
Currently Pelorus is forcing JIRA to follow very specific conventions around workflow. The type must be a **Bug** and priority **highest**. Secondly application label is required to be **"app.kubernetes.io/name"**.

Above should be changed to be configurable with defaults as current behavior.

@kpiwko prepared some changes, that are great, however they require a bit of split to address only this issue, so we can create PR out of it https://github.com/konveyor/pelorus/compare/v1.4.0-rc...kpiwko:jira-enhancements?expand=1

@kpiwko are you willing to create modified code that includes only changes described in this issue, so we can review and merge it?

**Comment by kpiwko** [comment]
hello @mpryc I can have a look at it next week.

Adding variables to cover label, priority and issue type, together with ability to provide JQL to override anything from that is an easy think to do.

That said, the most important aspect of the PR for me is to enable jira token auth as this is what my target jira instance is using.Any suggestion how to proceed with that one - https://github.com/konveyor/pelorus/issues/118?

**Comment by mpryc** [comment]
@kpiwko JIRA token is also perfectly reasonable request.

Just don't want to have one big PR with multiple issues in it.

If it's prepared as separate PR I am more then happy to review and merge or if you don't have bandwidth I am also happy to help here.

Note that there was a small rework on the auth function in pelorus so it may require rebase https://github.com/konveyor/pelorus/blob/master/exporters/failure/collector_jira.py#L42-L63

**Comment by mpryc** [comment]
@kpiwko I also noticed you have in your PR fix for getting more then 50 JIRA results, however I have implemented it slightly different way to be more robust: https://github.com/konveyor/pelorus/blob/master/exporters/failure/collector_jira.py#L80-L91

**Comment by kpiwko** [comment]
ok, so let me start with JIRA query flexibility PR @mpryc . Afterwards, I'll look into token part.

**Comment by mpryc** [comment]
With the merge of #466 I consider this as done.
