### ISSUE TITLE
add a helm chart option to prevent the deployment of the obsevability stack

### ISSUE THREAD

**Issue by raffaelespazzoli** [konveyor/pelorus#451]
prevent deploying Grafana and Prometheus. There can be deployment in which metrics are collected differently. For example using the user workload moniting stack.
ServiceMonitor and other Prometheus operator CR should be deployed, just the Prometheus operator and Prometheus instance should not. Same applies to grafana operator and grafana instance.

**Comment by KevinMGranger** [comment]
Related to #364 and #369

**Comment by mpryc** [comment]
I am closing this issue. Currently Helm Chart was moved into Pelorus Operator based on the helm charts.

The split of deployment/observability is tracked under discussion: https://github.com/konveyor/pelorus/discussions/809
