### ISSUE TITLE
Create a proper helm repo instead of using "localinstall" for helm

### ISSUE THREAD

**Issue by testlaben** [konveyor/pelorus#452]
Please - could you create a proper helm repo instead of relying on downloading the git repository and installing the charts with local helm?

We are unable to use your repository as a helm chart through ArgoCD - due to invalid charts setup.
(missing index.yaml and packages)
https://tech.paulcz.net/blog/creating-a-helm-chart-monorepo-part-1/

This has a good guide on how to set it up on github.

**Comment by mpryc** [comment]
We have released the Pelorus as an OpenShift operator available via Marketplace.

Here are docs on the Installation path:
  https://pelorus.readthedocs.io/en/latest/GettingStarted/Installation/

Closing this issue as it's not relevant anymore.
