### ISSUE TITLE
JIRA exporter does not give results if one of the projects is missing

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#455]
If we configure JIRA exporter in a way that scope of the projects is defined:

`PROJECTS=firstproject,secondproject,thirdproject`

and one of the projects is missing in JIRA, e.g. only secondproject is missing.

Then none of the issues are returned and JIRA exporter fails to feed data properly.

**Comment by mateusoliveira43** [comment]
1. What should be the desired behavior?
  - return issues from `firstproject` and `thirdproject` and log an error/warning?
  - return issues from `firstproject` and `thirdproject` and warn user olny in the frontend (grafana)?
2. We should only modify [this file](https://github.com/konveyor/pelorus/blob/master/exporters/failure/collector_jira.py) to solve the issue?
3. There are JIRA projects that we can use as test targets?

**Comment by mpryc** [comment]
> 1. What should be the desired behavior?
> 
> * return issues from `firstproject` and `thirdproject` and log an error/warning?

Log warning and continue to work with `firstproject` and `thirdproject`.


> 2. We should only modify [this file](https://github.com/konveyor/pelorus/blob/master/exporters/failure/collector_jira.py) to solve the issue?

Correct

> 3. There are JIRA projects that we can use as test targets?

We do have:
https://pelorustest.atlassian.net/jira/core/projects/FIRST/board

Please request to be added to this project and I'll approve (I think it's working out of request if not I will add your user once you provide me with atlassian.net one).

One project is enough for testing as second will be non-existing one.

**Comment by mateusoliveira43** [comment]
I could not request to be added to the project (I only receive a message that I have no access to it). What do you need to add me there?

**Comment by mpryc** [comment]
> I could not request to be added to the project (I only receive a message that I have no access to it). What do you need to add me there?

Added your e-mail to that project, needs now to be accepted by (I think) @weshayutin

**Comment by mateusoliveira43** [comment]
I have access now, thanks! I will try to work on the fix on Sunday.
