### ISSUE TITLE
Defaults for exporters should be defined in the helm charts such that a user has a minimum install working.

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#476]
So.. deploytime exporter will automatically be configured via configmaps in the default values.yaml

**Comment by KevinMGranger** [comment]
What do you mean by this? The default chart already has a deploytime exporter running, but every other exporter requires setting up credentials.

**Comment by mpryc** [comment]
I believe now we have very minimal default with good set of data within configmap to close this issue once https://github.com/konveyor/pelorus/pull/516 is merged.
