### ISSUE TITLE
Backup and Restore prom / thanos data to filesystem

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#477]

**Comment by weshayutin** [comment]
@mpryc is this a valid issue, perhaps I misunderstood how we pelorus / Prometheus wrote data to an external source?

**Comment by mpryc** [comment]
@weshayutin I would leave it open until I really test re-deployment of Pelorus with the previously generated data using s3 bucket.

**Comment by mpryc** [comment]
Same as #139, closing.
