### ISSUE TITLE
Research generic commit time to raise the level of certainty to ditch tekton specific support

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#478]

**Comment by weshayutin** [comment]
This is still being debated in that perhaps a generic commit time is more appropriate.

**Comment by KevinMGranger** [comment]
The current state of things:

I have an [old Draft PR to add Tekton Support](https://github.com/konveyor/pelorus/pull/333/). ([tekton issue](https://github.com/konveyor/pelorus/issues/224))

However, tekton pipelines are infinitely customizable. It uses some basic heuristics to see what data it could get.

A more flexible solution is to allow custom labels, and to add functionality for that.

We already have a basic tekton demo in the demos dir, it would just need one or two steps added for that.
