### ISSUE TITLE
ReadTheDocs incorrectly handles new releases

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#496]
When a new release tag is created, we should see:

- `pelorus.readthedocs.io/en/$TAG_HERE/` is created
- `pelorus.readthedocs.io/en/stable/` shows the same content as the above
- `pelorus.readthedocs.io` redirects to `/en/stable`

This is desirable for SEO purposes: a search engine should not point to outdated information, but a permalink should still exist.

Actual behavior:

- `pelorus.readthedocs.io/en/$TAG_HERE/` is created
- `pelorus.readthedocs.io/en/stable/` shows outdated content
- `pelorus.readthedocs.io` redirects to `/en/$TAG_HERE`

It's a bit confusing because there are two different spots for GitHub integration. We have (had?) a webhook set up in GitHub but it seems to not be working as expected. I recall it complaining about errors but we ignored it since it _appeared_ to work.

**Comment by KevinMGranger** [comment]
Our stable branch isn't updating either. Did we have automation for that? I can't remember.

**Comment by mpryc** [comment]
We will have this under bigger discussion around versioning of the charts, git releases, exporter container tags, documentation within OpenShift Pelorus instance object and pelorus-operator.

Moving to [#811 ](https://github.com/konveyor/pelorus/discussions/811)
