### ISSUE TITLE
doc for the deployment exporter should explain how to label all "special" builds e.g. binary for example.

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#510]
Recreate:
oc create namespace binary-build
oc new-build python --name=python-binary-build4 --binary=true -n binary-build
oc label bc python-binary-build4 app.kubernetes.io/name=python-binary-build4 -n binary-build
oc start-build bc/python-binary-build4 --from-file=./app.py --follow -n binary-build
oc get builds -n binary-build
oc -n binary-build annotate build python-binary-build4-1 --overwrite \
io.openshift.build.commit.id=7810f2a85d5c89cb4b17e9a3208a311af65338d8 \
io.openshift.build.source-location=http://github.com/konveyor/pelorus
oc -n binary-build new-app python-binary-build4

* The build has labels:
```
app.kubernetes.io/name=python-binary-build4
build=python-binary-build4
buildconfig=python-binary-build4
openshift.io/build-config.name=python-binary-build4
openshift.io/build.start-policy=Serial
```

This is likely due to:
https://github.com/konveyor/pelorus/blob/master/exporters/deploytime/app.py#L218

```
[whayutin@thinkdoe BUILD]$ oc get all
NAME                                        READY   STATUS      RESTARTS   AGE
pod/python-binary-build4-1-build            0/1     Completed   0          4m15s
pod/python-binary-build4-5747676745-68drq   1/1     Running     0          2m51s

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/python-binary-build4   ClusterIP   172.30.197.209   <none>        8080/TCP   2m52s

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/python-binary-build4   1/1     1            1           2m52s

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/python-binary-build4-5747676745   1         1         1       2m51s
replicaset.apps/python-binary-build4-5f575c5f87   0         0         0       2m52s

NAME                                                  TYPE     FROM     LATEST
buildconfig.build.openshift.io/python-binary-build4   Source   Binary   1

NAME                                              TYPE     FROM     STATUS     STARTED         DURATION
build.build.openshift.io/python-binary-build4-1   Source   Binary   Complete   4 minutes ago   54s

NAME                                                  IMAGE REPOSITORY                                                                     TAGS     UPDATED
imagestream.image.openshift.io/python-binary-build4   image-registry.openshift-image-registry.svc:5000/binary-build/python-binary-build4   latest   3 minutes ago
[whayutin@thinkdoe BUILD]$ 

```

**Comment by KevinMGranger** [comment]
Deploytime wouldn't look at builds. It looks at replication controllers and replica sets. If something isn't appearing to it, then it's the the DeploymentConfig is missing the label from its template.

**Comment by weshayutin** [comment]
@KevinMGranger ya.. try it :) it's not working when the labels are there.. The issue we think is that the replicationset name $-name-xyz123 does not match the k8s.name=name

**Comment by KevinMGranger** [comment]
Can you give the full YAML for `pod/python-binary-build4-5747676745-68drq` and `replicaset.apps/python-binary-build4-5747676745` ?

**Comment by weshayutin** [comment]
@KevinMGranger please do not close issues w/o providing the proper documentation that an issue is NOT an issue or reproducable.  It's bad form IMHO to do to anyone.  Thank you.

**Comment by mpryc** [comment]
The new-app step needs to be labeled so the pod also inherits the label, checked and works with the following commands:

```
NS=mongo-persistent
NAME=python-binary-build

oc create namespace "${NS}"

oc new-build python --name="${NAME}" --binary=true -n "${NS}"
oc start-build "bc/${NAME}" --from-file=./app.py --follow -n "${NS}"


oc -n "${NS}" annotate build "${NAME}-1" --overwrite \
io.openshift.build.commit.id=7810f2a85d5c89cb4b17e9a3208a311af65338d8 \
io.openshift.build.source-location=http://github.com/konveyor/pelorus

oc -n "${NS}" new-app "${NAME}" -l "app.kubernetes.io/name=${NAME}"

```

**Comment by weshayutin** [comment]
@mpryc thanks.. that is a helpful comment.  I will check out the doc on the above and see what we have on it.

**Comment by KevinMGranger** [comment]
Should we change the issue name to reflect that it's a labelling issue? Or create a new issue instead? I keep getting confused when I see notifications for this.

**Comment by weshayutin** [comment]
There is some doc on this now, let's re-review to be certain.
