### ISSUE TITLE
Track GitHub Releases as "Deployments"

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#531]
This is related to dogfooding Pelorus more than anything else.

If we want to track our own Software Delivery Performance, our "deploy to production" metric is measured by how often we're making new releases. We should be able to measure that with an exporter.

**Comment by weshayutin** [comment]
@KevinMGranger https://github.com/konveyor/pelorus/pull/471 still has a hold on it.  Can you please /unhold 
thank you!
