### ISSUE TITLE
committime: GIT_USER should override USER when both are set

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#553]
While `$USER` is cleaner for running exporters in a container, where the user running it doesn't matter, it makes for hard-to-spot errors in local testing. Setting `$GIT_USER` does nothing!

(This would be easier to spot with #554.)

In `upgrade_legacy_vars`, instead of
```python
git_user = utils.get_env_var("GIT_USER")
if not utils.get_env_var("USER"):
    os.environ["USER"] = git_user
```
we should have:
```python
git_user = utils.get_env_var("GIT_USER")
user = utils.get_env_var("USER")
os.environ["USER"] = git_user or user
```

**Comment by mpryc** [comment]
I am fine with that, however I think it's better to have user over git_user, so:

```
os.environ["USER"] = user or git_user
```

This way we do have backwards compatibility.

Another thing to consider is actually moving away from USER as in POSIX.1-2017 the USER is actually advised to not use it as it may conflict with other apps/vars:

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

USER env var represents in shell usually represents the currently running user, so it's set, which may cause inappropriate USER to be used with the TOKEN/password if not set.

**Comment by KevinMGranger** [comment]
Doing `user or git_user` wouldn't fix the issue, though.

I'm not sure I understand the second half. Do you mean we shouldn't use `USER` in the first place? Because I agree. I think either `GIT_USER` or `API_USER` makes sense.
