### ISSUE TITLE
All exporters should use unified configuration management, and log their configuration

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#554]
We have some manual logging, but this will help with debugging greatly. The lack of this made solving #553 really hard.

Unifying this would make sure we don't miss any new configuration that gets added. It's also better for security-- if we leave everything up to manual logging, someone could accidentally log credentials!

The way exporters are configured has always been inconsistent, and sometimes messy. A cleanup of this whole area would be valuable.

**Comment by mpryc** [comment]
This was resolved by @KevinMGranger with the configuration rework.
