### ISSUE TITLE
CI: Jira failure exporter

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#571]
TO-DO create CI for Backend

**Comment by mpryc** [comment]
Closing as it's now covered by PR jobs and also periodic job configs with default JIRA workflow and custom JIRA workflow:

- https://github.com/konveyor/mig-demo-apps/blob/master/apps/todolist-mongo-go/pelorus/values.yaml#L84-L115
- https://github.com/konveyor/mig-demo-apps/blob/master/apps/todolist-mongo-go/pelorus/periodic/quay_images_latest.yaml#L80-L109

The above are invoked by Makefile from our script:
- https://github.com/konveyor/pelorus/blob/master/Makefile#L138-L144
- https://github.com/konveyor/pelorus/blob/master/scripts/run-pelorus-e2e-tests#L451-L471

By various OpenShift versions:
- https://github.com/openshift/release/tree/master/ci-operator/config/konveyor/pelorus

For the PR and periodic jobs:
- https://github.com/openshift/release/tree/master/ci-operator/jobs/konveyor/pelorus

Note we will be working on getting this compatible with Pelorus Operator workflow, but the general CI workflow will stay as it is, just some config files will get updated. Here is prepared config file:
- https://github.com/konveyor/mig-demo-apps/blob/master/apps/todolist-mongo-go/pelorus/values_v1alpha1_pelorus.yaml
