### ISSUE TITLE
API_USER and TOKEN should _both_ be present or _both_ be absent.

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#578]
> Bitbucket requires *both* API_USER and TOKEN to be set. If API_USER or TOKEN is set and second is unset, then it will fall back to anonymous authentication without giving error:

```
401 Client Error: Unauthorized for url: https://bitbucket.org/api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471
```

> I think we should check if both are set or both are unset, otherwise users will silently use non-authorized API calls even if they requested authorized ones.

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/issues/465#issuecomment-1191336433_

**Comment by weshayutin** [comment]
scoped to bitbucket and perhaps other exporters, specifically not needed for github backends
