### ISSUE TITLE
Commit time exporter should track deployed apps and not all the builds

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#583]
The Commit Time exporter should track and report only those apps that has running pods and not all the builds.

Currently creating e.g. binary build and annotating it causes commit time to show the commit timestamp, for example

```
Collected commit_timestamp{ namespace=bitbucket-binary, app=bitbucket-binary, commit=e2c4ef00468dfc10aad1bd2d4c9d470160a7f471, image_sha=sha256:7466229c5a9e241b6b32e48174e178ad8a5b0858a1d6617f27c9df87286b829d 
} 1657806414.0
```

But the issue is that there may be 0 pods running such application, meaning pelorus is tracking builds and not deployed applications.

**Comment by KevinMGranger** [comment]
To clarify, that it tracks _all_ builds is not an issue. The measure only looks at correlated metrics.

`min by (app, commit) (deploy_timestamp - on(app,image_sha) group_left(commit) commit_timestamp)`

**Comment by KevinMGranger** [comment]
As for why we can't just use pods for the sake of efficiency, or flexibility for tekton support, I talked about this with Eric.

> If I build an image today, and don't deploy the image until tomorrow, by the time that happens, the build could have been pruned
> and so then I would have a deployment, for which I have no build info

This is a real risk.

**Comment by etsauer** [comment]
The other reason you can't reference running pods is because you might be comparing builds in one cluster (development) to pods in another (production) so the commit exporter won't have that information

**Comment by mpryc** [comment]
@etsauer thank you for the clarification.

How about scenario where user would like to annotate object with URI and git instead of relying on the Build?

Maybe annotated objects should be deployments or replication controllers as this allows to directly map commit time to the app being deployed to the production?

In other words I do understand the Build use case, however with annotations we do allow to include commit uri/ hash and this data will be available to the commit time exporter.

**Comment by KevinMGranger** [comment]
@mpryc we threw around that idea before, but I think the Custom Resource solution might be better.

**Comment by etsauer** [comment]
@mpryc yes in that case, the build doesn't matter. IMO The right thing to do is to annotate the _artifact_ being deployed (e.g. the image) and trace that artifact through its lifecycle.

**Comment by KevinMGranger** [comment]
Closing as we've determined why we shouldn't do this.
