### ISSUE TITLE
We should "productize" pelorus a bit more by auto-building our exporter images and pushing them to Quay.io

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#63]
Rather than having to run our image builds in each cluster, we should provide already built images for our exporters.

**Comment by etsauer** [comment]
we can use the [s2i github action](https://github.com/redhat-cop/github-actions/tree/master/s2i) for this

**Comment by jtudelag** [comment]
We can give a try to the new official Red Hat actions: https://github.com/marketplace?query=redhat

**Comment by etsauer** [comment]
We have images being published to Quay.io now. https://quay.io/organization/pelorus

Next step is to update the helm charts to consume those images.

**Comment by etsauer** [comment]
I believe we can close this issue right @KevinMGranger ?

**Comment by KevinMGranger** [comment]
The images are definitely being published, yes. But we want using them be the end-user facing workflow, right? Or should we make a separate issue for that?

**Comment by mpryc** [comment]
I've created PR #370  which fixes build of images that are being published to quay.io. Next step is to used them in the deployment. That was another issue #358. I've created #373 to track issue where we should use images from registry.

**Comment by mpryc** [comment]
Closing as per https://github.com/konveyor/pelorus/issues/63#issuecomment-1276131946
