### ISSUE TITLE
Move scripts and queries in helm charts to separate files

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#652]
Right now, there are a few scripts run as cronjobs / jobs embedded in our helm charts. There are also prometheus queries embedded in a PrometheusRules object, as well as in verbose JSON for the grafana dashboard.

This makes inspecting these resources, using tooling on them, and even reasoning about them difficult.

[You can access files adjacent to helm templates](https://helm.sh/docs/chart_template_guide/accessing_files/). We could pull them in at install time!

By moving them out separately, we would have a nicer experience for tooling.

Examples of tooling we'd now get to use:

- promtool for testing (this already exists, but uses sed to pull data out of the PrometheusRules)
- shellcheck for some of the bash scripts (or perhaps rewriting those in python)
- syntax highlighting / formatting in the editor of your choice

**Comment by mpryc** [comment]
At this time I think we have 0 relevant scripts for the pelorus-operator use case.

We do have:
- One test script to be ran when `helm test` is invoked, but to be honest I don't know/don't think it's utilized by pelorus-operator. I couldn't find such job in the deployment made by operator :
   https://github.com/konveyor/pelorus/blob/master/charts/pelorus/templates/tests/pelorus-grafana-test-job.yaml#L24-L90

- Two scripts which are used to install operator via Helm chart, but operator uses OLM, so they are not relevant:
    https://github.com/konveyor/pelorus/blob/master/charts/operators/templates/installplan-approval-job.yaml#L18-L47
    https://github.com/konveyor/pelorus/blob/master/charts/operators/templates/delete-csv-hook.yaml#L18-L21

@KevinMGranger  should we keep this issue open?

**Comment by mpryc** [comment]
There is also one PR https://github.com/konveyor/pelorus/pull/227 open to cover prometheus deployment, which I think could be closed if we agree that this bug can be closed.

Question:
 - should we have some additional tests in the pelorus-operator to similarly check the Pelorus stack or maybe operators have already some functionality that covers it?

**Comment by KevinMGranger** [comment]
I agree that we don't need to separate the scripts anymore... because they're gone! Yay!

We should consider how we test out install though, which means #227 should stay open.
