### ISSUE TITLE
Deploytime exporter reports too many same rows

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#657]
If the deploytime monitors multiple namespaces and apps, data can grow really fast.

For each subsequent unique pair of namespace/app there is a new deploy_timestamp with the previous apps already reported.

In case we have 1 pair, there will be 1 deploy_timestamp. If we have 2 pairs, then we will see 1 + (1+1) = 3 rows.
For 3 pairs, we will get 1 + (1+1) + (1+1+1) = 6 rows, meaning we are looking here at sum of an = n+1 numerical sequence.

Attached file with 528 deploy_timestamp, where only 32 should be reported.

For example at 180 apps we would have 16290 lines instead of 180, that would make our deploy time exporter pretty unusable, for 300 apps 45150 lines.
[rows.txt](https://github.com/konveyor/pelorus/files/9608423/rows.txt)

**Comment by weshayutin** [comment]
thanks for writing this up.

**Comment by KevinMGranger** [comment]
This happens because the `yield metric` is inside the `for m in metrics` instead of being outside it.
