### ISSUE TITLE
Design - Pelorus OpenShift Community Operator

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#674]
See [hackmd from design meeting](https://hackmd.io/Atgnm51LR2ud13d1nzeK0g?view)

**Comment by KevinMGranger** [comment]
Reorganization summary from old notes, mostly followed in the mentioned PRs:

- [ ] #696 / #686
  - Move exporters under /charts (not nested under pelorus chart)
  - Move items to library charts
  - Create an alternate chart (i.e. /charts/pelorus-operator) with an alternate values.yml (to lean on generation as much as possible)

- [ ] #715: generate "starter" operator with operator-sdk generator
  - [ ] tag this step so we have a baseline for future operator-sdk versions

General:
- [ ] continuously verify with CI that we aren’t breaking this for existing users
- [ ] create UI for user input

**Comment by weshayutin** [comment]
Pelorus community operator has been released.
