### ISSUE TITLE
Pre-commit checks don't support forking

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#692]
It seems that when a user tries to make a commit, the pre-commit chart linting step makes an assumption that the `konveyor/pelorus` remote as set as `origin` in the users local git setup. If its not, the lint step will fail with the following error:

```bash
./scripts/install_dev_tools -v .venv -c ct && \
. .venv/bin/activate && \
ct lint --config ct.yaml
Cleaning up temporary files
Linting charts...
------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
Error: failed linting charts: failed identifying charts to process: failed running process: exit status 128
failed linting charts: failed identifying charts to process: failed running process: exit status 128
make: *** [Makefile:221: chart-lint] Error 1
🐚 📋 Linting shell scripts with shellcheck
/bin/shellcheck demo/demo-tekton.sh scripts/create_release_pr scripts/install_dev_tools scripts/pre-commit scripts/run-mockoon-tests scripts/setup-pre-commit-hook scripts/run-pelorus-e2e-tests
make: Target 'lint' not remade because of errors.


Linting failed. Check the above output for hints.


If you must, use git commit --no-verify to bypass these checks.
```

This setting seems to discourage repository forking, which I don't think we want. Ideally this setting could either dynamically figure out the right remote to compare against for chart linting, or allow the user to set that up somehow, OR at worst default to expect the user to be using a fork and have `konveyor/pelorus` set as `upstream` instead of `origin`.

**Comment by mateusoliveira43** [comment]
I think I never had this issue, but I could reproduce this in here https://github.com/konveyor/pelorus/actions/runs/4077545942/jobs/7026700972

gone work to fix it

**Comment by mateusoliveira43** [comment]
@etsauer I was only able to reproduce this error running locally `git remote remove origin` before running `make chart-lint` (which the script pre-commit runs under the rug) and as specified here https://github.com/helm/chart-testing/issues/186 : running `git clone` with `--depth 1`.

Do you remember how this error occurred to you?

I believe adding in the docs a "run git clone your_fork" would be enough to avoid this. but I added a little script in here as well https://github.com/konveyor/pelorus/pull/685. tell me what you think is better

**Comment by KevinMGranger** [comment]
I paired with Mateus. We found that it was a separate but semi-related issue.

As for this issue:

`ct lint` will let you specify a remote name. I guess we can check the output of `git remote -v, see what matches `konveyor/pelorus`, and error out if it's missing.
