### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by mateusoliveira43** [konveyor/pelorus#697]
Hi everyone :wave:
Thanks for this awesome Project!

The [link](https://pelorus.readthedocs.io/) to Pelorus documentation in the `README.md` file takes to the old version of the documentation (with the readthedocs theme). I also noticed that with the new theme, I cannot change the version (I can only see latest). Is this a bug? 

I ran `grep -Inr 'https://pelorus.readthedocs.io/' .` in the project root and found only other file (`samples/todolist_failure_restore.md`) that takes to the old version. Changing this two links can be a partial solution.

I also suggest adding the link to the documentation in the About section (in the right, along releases and packages) of the repository. [An example of how it would look](https://github.com/mateusoliveira43/cly).

**Comment by KevinMGranger** [comment]
The old version part is deliberate-- we want it to point to the latest stable release, and we haven't had a release since the theme change.

You're right about the version change not working! We need to investigate that.

I just added the link to our documentation to the About section. Good call!

**Comment by mpryc** [comment]
Closing. Currently we are pointing to latest. We need to define a clear process of the docs/image tags for each release.
