### ISSUE TITLE
dev env setup handle golang cert issues on macOS

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#707]
There's an [outstanding issue](https://github.com/golang/go/issues/52010) with go's x509 library that broke invalid certificate handling on macOS. If you're using some local cluster with self-signed certs, ignoring their validity won't work.

If you're using OpenShift Local / CRC, then their bundled `oc` version actually works around this! But I always forget about that when remaking my dev environment 😅.

A reminder would be nice.

**Comment by KevinMGranger** [comment]
Alternatively, since the workaround is to use the 4.10 version of `oc`, maybe the script should just use that version on macOS for now?

https://bugzilla.redhat.com/show_bug.cgi?id=2097830

**Comment by mpryc** [comment]
@KevinMGranger #709 is merged, however we should track the issue with the oc on Mac somewhere so it will get updated when it's fixed.
