### ISSUE TITLE
Update outdated github actions

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#711]
Some of them are causing deprecation warnings to be emitted: https://github.com/konveyor/pelorus/actions/runs/3414501849

**Comment by mateusoliveira43** [comment]
There is the [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) that can do this automatically (but this was not the reason of the update).

Example of use: https://github.com/tiangolo/fastapi/blob/master/.github/dependabot.yml

**Comment by KevinMGranger** [comment]
We should look into that for both GH actions as well as python dependencies!
