### ISSUE TITLE
pelorus-operator-controller-manager-* pod is going into CrashLoopBackOff / oomkilled

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#731]
Increasing memory and cpu resources does fade out the issue, but it's still existing over time. Pelorus get's deployed correctly, just manager is crashing with oomkilled. Maybe it's related to the log growing up in the manager pod.

pelorus-operator-controller-manager-* pod is going into CrashLoopBackOff, however pelorus is deployed correctly.

I suspect there may be a problem with proper resources to that pod ?

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/issues/715#issuecomment-1329000462_

**Comment by KevinMGranger** [comment]
Potentially solved by https://github.com/operator-framework/operator-sdk/pull/6026
