### ISSUE TITLE
Consider running doctests

### ISSUE THREAD

**Issue by KevinMGranger** [konveyor/pelorus#754]
They're useful for small utility functions, and make sure we're not "lying" in the documentation.

Pytest even has some support for them, although I'm not fully familiar with how they do it: https://docs.pytest.org/en/7.1.x/how-to/doctest.html

**Comment by mpryc** [comment]
Adding CI label as I believe this should be covered by the new github action?

**Comment by KevinMGranger** [comment]
Yes, but we can and should integrate it into our unit test strategy also.
