### ISSUE TITLE
Documentation: Configuration Docs Wrong Instructions?

### ISSUE THREAD

**Issue by stratus-ss** [konveyor/pelorus#764]
The [documentation](https://pelorus.readthedocs.io/en/latest/Configuration/) linked in the installed operator says

```
The recommended practice is to make a copy of the one [values.yaml](https://github.com/konveyor/pelorus/blob/master/charts/pelorus/values.yaml) file and [charts/pelorus/configmaps/](https://github.com/konveyor/pelorus/blob/master/charts/pelorus/configmaps) directory, and store in in your own configuration repo for safe keeping, and updating.
```

However there is no `configmaps` directory at that location. I assume that the location should be `charts/configmaps` is this correct?

**Comment by mateusoliveira43** [comment]
They are stored here today?

- https://github.com/konveyor/pelorus/blob/master/charts/pelorus/subcharts/exporters/templates/default_configmaps.yaml
- https://github.com/konveyor/pelorus/blob/master/pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/default_configmaps.yaml

**Comment by mateusoliveira43** [comment]
Added the right path in https://github.com/konveyor/pelorus/pull/799 under `/en/latest/GettingStarted/configuration/PelorusExporters/#env_from_configmaps` endpoint
