### ISSUE TITLE
Add how to run e2e script to documentation

### ISSUE THREAD

**Issue by mateusoliveira43** [konveyor/pelorus#768]
In https://github.com/konveyor/pelorus/pull/759 I commented the e2e script part from `docs/Demo.md`. 

Add it back (probably better in development section).

**Comment by mpryc** [comment]
@mateusoliveira43 thanks. we will need to ensure the steps are clean and works with our operator. I am unsure if it should go under developer section as it's demo for the user and not developer.

Running e2e-tests should be covered by a developer doc.

**Comment by mpryc** [comment]
Tekton takes over this script. Documentation for the demo is updated and do not contain this script anymore. Not valid. Closing.
