### ISSUE TITLE
Consider using Tabs/spaces in our docs

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#803]
@mateusoliveira43 we can change this to Tabs, but other exporter docs also uses definition lists, so we want to be same across other docs.

_Originally posted by @mpryc in https://github.com/konveyor/pelorus/pull/798#discussion_r1084014206_

**Comment by KevinMGranger** [comment]
Description lists are the right semantic for this, no?

**Comment by mpryc** [comment]
Markdown generates from `: foo` the following html:
```html
<dl>
  <dd>foo</dd>
</dl>
```

So it's '<dl>' with one '<dd>'.

@KevinMGranger you are right that it's called "Description list" by the HTML standard:

https://www.w3schools.com/tags/tag_dl.asp

**Comment by KevinMGranger** [comment]
I'd actually been calling it a definition list for _years_ until I looked it up just now 😆
