### ISSUE TITLE
Write pelorus usage docs

### ISSUE THREAD

**Issue by etsauer** [konveyor/pelorus#85]
Currently all of our documentation deals with deploying and configuring pelorus infrastructure. We need to write docs that deal with the usage of Pelorus once it is up and running. Some possible topics include:

- How pelorus collects data (and how to generate some)
- Features of the Software Delivery Performance dashboard
- How to read and interpret the data

**Comment by etsauer** [comment]
This probably needs to be broken up into multiple items, but here are some of the questions we are being asked.

- What exactly IS pelorus? What isn't it?
- How do the exporters work? What do they collect, and how?
- How does Pelorus measure activity going on in my feature branches, vs master branch, and how do I distinguish which ones should be "counted"?

**Comment by prakritiverma** [comment]
Needs to be scoped after newest documentation
