### ISSUE TITLE
Create documentation for the webhook-exporter

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#857]
The webhook exporter is a new type of exporter and should be documented on how to communicate with it. 

Also a well defined schema for different metrics should be part of that documentation, so the users should have clear instructions what data is expected to be delivered.

For more information please see the relevant PRs:
https://github.com/konveyor/pelorus/pull/844
https://github.com/konveyor/pelorus/pull/836

**Comment by mateusoliveira43** [comment]
Important: add how to create custom plugins in the documentation
