### ISSUE TITLE
Webhook exporter does not validate timestamp properly

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#867]
It's possible to cause webhook exporter to fail if the wrong timestamp format is provided, e.g. string and not the EPOCH int timestamp "1s57933657".

This causes pod to fail with the following traceback:

```
File "/opt/app-root/lib64/python3.9/site-packages/prometheus_client/exposition.py", line 195, in sample_line
return f'{line.name}{labelstr} {floatToGoString(line.value)}{timestamp}\n'
File "/opt/app-root/lib64/python3.9/site-packages/prometheus_client/utils.py", line 9, in floatToGoString
d = float(d)
ValueError: ("could not convert string to float: '1s57933657'", Metric(failure_creation_timestamp, Failure Creation Timestamp, gauge, , [Sample(name='failure_creation_timestamp', labels={'app': 'mongo-todolist', 'failure_id': 'MONGO-1'}, value='1557933657', timestamp=None, exemplar=None), Sample(name='failure_creation_timestamp', labels={'app': 'mongo-todolist', 'failure_id': 'MONGO-1'}, value='1s57933657', timestamp=None, exemplar=None)]))
```

**Comment by mpryc** [comment]
To reproduce the issue:
Start webhook exporter in one terminal
```shell
make dev-env
source .venv/bin/activate
python exporters/webhook/app.py
```

From another teminal send some fake data:
```shell
curl -X POST http://localhost:8080/pelorus/webhook -H "Content-Type: application/json" -H "User-Agent: Pelorus-Webhook/test" -H "X-Pelorus-Event: failure" -d '{"app": "mongo-todolist","failure_id": "MONGO-1","failure_event": "created", "timestamp": "15579ff33657"}'
```

Open web-page with `metrics`:
http://localhost:8080/metrics

Expected result:
  metrics for prometheus visible

Actual result:
 * "Internal Server Error"
 * Traceback  in the terminal where python app.py was running
 * http://localhost:8080/metrics no longer accessible

**Comment by mateusoliveira43** [comment]
Sending timestamp as `None` still breaks code. I believe the problem is setting None as the default in here https://github.com/konveyor/pelorus/blob/master/exporters/webhook/models/pelorus_webhook.py#L54

Writing as `timestamp: int = Field(ge=1262307661, le=2840144461)` prevents this.

Write test to catch this use case and test a little more.
