### ISSUE TITLE
Chart lint to be updated to include -rc.X suffix

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#868]
I updated as we discussed in https://github.com/konveyor/pelorus/discussions/811 but chart lint breaks. How should we proceed?

_Originally posted by @mateusoliveira43 in https://github.com/konveyor/pelorus/pull/866#discussion_r1126872993_

**Comment by mateusoliveira43** [comment]
Closing as we discussed solution

Instead of `x.y.z` -> `x.y.z-rc.1` -> ..., we will do `x.y.z` -> `x.y.z+1-rc.1` -> ...
