### ISSUE TITLE
operator v.0.8 default install, webhook exporter route needs  route + /metrics

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#888]
0. The following was seen after a full default install, no customization's to the exporters. 

INFO[0012] Waiting for ClusterServiceVersion "pelorus/pelorus-operator.v0.0.8" to reach 'Succeeded' phase 
INFO[0012]   Waiting for ClusterServiceVersion "pelorus/pelorus-operator.v0.0.8" to appear 
INFO[0040]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.8" phase: InstallReady 
INFO[0041]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.8" phase: Installing 
INFO[0061]   Found ClusterServiceVersion "pelorus/pelorus-operator.v0.0.8" phase: Succeeded 
INFO[0061] OLM has successfully installed "pelorus-operator.v0.0.8" 

woot..  next step..
1.  create the pelorus-sample instance w/ no changes, use all defaults.

To get to webui logs of the webhook exporter one has to navigate to the route + /metrics in order to see:
http://webhook-exporter-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com/metrics
```
webhook_processed_total 0.0
# HELP webhook_processed_created Number of processed webhooks
# TYPE webhook_processed_created gauge
webhook_processed_created 1.6785702379354002e+09
# HELP commit_timestamp Commit timestamp
# TYPE commit_timestamp gauge
# HELP deploy_timestamp Deployment timestamp
# TYPE deploy_timestamp gauge
# HELP failure_creation_timestamp Failure Creation Timestamp
# TYPE failure_creation_timestamp gauge
# HELP failure_resolution_timestamp Failure Resolution Timestamp
# TYPE failure_resolution_timestamp gauge
```

The other exporters do not need a suffix on the url to get to the logs.

```
(.venv) [whayutin@thinkdoe pelorus]$ oc get route -n pelorus
NAME                  HOST/PORT                                                                            PATH   SERVICES              PORT            TERMINATION          WILDCARD
committime-exporter   committime-exporter-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com          committime-exporter   http                                 None
deploytime-exporter   deploytime-exporter-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com          deploytime-exporter   http                                 None
grafana-route         grafana-route-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com         /      grafana-service       grafana-proxy   reencrypt            None
prometheus-pelorus    prometheus-pelorus-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com           prometheus-pelorus    web-tls         reencrypt/Redirect   None
webhook-exporter      webhook-exporter-pelorus.apps.cluster-wdh02152023a.wdh02152023a.mg.dog8code.com             webhook-exporter      http                                 None

```

**Comment by weshayutin** [comment]
ah.. I think by default it's pointing to /webhook/pelorus?
https://pelorus.readthedocs.io/en/latest/GettingStarted/configuration/ExporterWebhook/#webhook-endpoint-uri

**Comment by mateusoliveira43** [comment]
No, the default is the root `/`, which doesn't have anything

I think this is easy to fix, I will try to fix this when I have time

**Comment by mateusoliveira43** [comment]
I have taken a look into how the other exporters work, and their root `/` is the same endpoint as the `/metrics` endpoint (`committime`, for example), right @mpryc?

One solution can be
```diff
--- a/exporters/webhook/app.py
+++ b/exporters/webhook/app.py
@@ -24,7 +24,7 @@ from pathlib import Path
 from typing import Dict, Optional, Type
 
 from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response
-from fastapi.responses import PlainTextResponse
+from fastapi.responses import PlainTextResponse, RedirectResponse
 from prometheus_client import Counter, generate_latest
 from prometheus_client.core import REGISTRY
 
@@ -218,6 +218,10 @@ async def pelorus_webhook(
 async def metrics():
     return generate_latest()
 
+@app.get("/")
+async def redirect_to_metrics():
+    return RedirectResponse(url='/metrics')
+
 
 if __name__ == "__main__":
     import uvicorn
```

**Comment by mateusoliveira43** [comment]
Another change I would made is to remove the generated endpoints of FastAPI (so we only have `/metrics` and `/pelorus/webhook`)

```diff
--- a/exporters/webhook/app.py
+++ b/exporters/webhook/app.py
@@ -163,7 +163,12 @@ async def get_handler(user_agent: str) -> Optional[Type[PelorusWebhookPlugin]]:
 
 
 # TODO App Module
-app = FastAPI(title="Pelorus Webhook receiver")
+app = FastAPI(
+    title="Pelorus Webhook receiver",
+    openapi_url=None,
+    docs_url=None,
+    redoc_url=None,
+)
 
 
 @app.post(
```

**Comment by mpryc** [comment]
> 

They have two endpoints "/" and "/metrics". I don't think we have to advertise the "/" by default prometheus goes to the "/metrics"

**Comment by mpryc** [comment]
Yes I am fine removing the generated ones (api, docs, redoc, note there is a healthcheck of running exporter pod, so need to ensure it's still correct.)

**Comment by mpryc** [comment]
Each webhook instance has one route and two endpoints:

```
<route>/metrics

<route>/pelorus/webhook
```

The rest is garbage, so we can either remove "<route>/" endpoint or make it same as "<route>/metrics" to be similar with other exporters, but I am not sure it's really required...

**Comment by weshayutin** [comment]
both urls are live, but the route should expose /metrics 1. because it's consistent across the other exporters and 2. it provides feedback to the user.

The docs nicely point to where to post data to .. so we're covered there.

**Comment by mpryc** [comment]
Updated the webhook with slightly different approach, which gives exactly the same result as other exporters.

The `/metrics` was a luck as `/whatever` would also work as an endpoint. Now webhook is behaving for the prometheus endpoint exactly same way as other exporters (doesn't mean it's really required or used by anyone, just nice to have imo).

**Comment by mateusoliveira43** [comment]
I would create an issue about this behavior, having the root copy the `/metrics` endpoint for The OpenShift route is ok, but having every endpoint go to `/metrics` seems to much

**Comment by mpryc** [comment]
@mateusoliveira43 it's what every other exporter does...

**Comment by mateusoliveira43** [comment]
yes, but I think it is wrong (but no need to rush to fix this)

Or are there advantages of redirecting all to `/metrics` route?

**Comment by mpryc** [comment]
I would actually prefer to have *only* `/metrics` route and do not show anything in the default route. Why to tell anyone that prometheus exporter is running there?

**Comment by mpryc** [comment]
For prometheus exporter we can also write our own handler, but I am sure it's not something important enough to stop our 0.0.5 release...

**Comment by mateusoliveira43** [comment]
Agree with both. I will create a discussion about this

For now, we keep the way it is (all routes redirecting to `/metrics`)
